version: '3.2'
services:
  valet:
    build:
      context: .
      args:
        PHP_VERSION: $PHP_VERSION
        DEV_USER: $DEV_USER
        DOMAIN_SUFFIX: $DOMAIN_SUFFIX
    image: egordm/wde:${PHP_VERSION}
    container_name: wde-${PHP_VERSION}
    depends_on:
      - db
    volumes:
      - type: bind
        source: $DOMAIN_PATH
        target: /home/$DEV_USER/domains
      - type: bind
        source: ./storage/valet/certificates
        target: /home/$DEV_USER/.valet/Certificates
      - type: bind
        source: ./storage/valet/log
        target: /home/$DEV_USER/.valet/Log
      - type: bind
        source: ./storage/valet/nginx
        target: /home/$DEV_USER/.valet/Nginx
    networks:
      dev_net:
        ipv4_address: 172.18.18.200

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    volumes:
      - db-store:/var/lib/mysql
    networks:
      dev_net:
        ipv4_address: 172.18.18.100
    tty: true
    stdin_open: true

volumes:
  db-store:

networks:
  dev_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.18.18.0/24
